<a href="https://colab.research.google.com/github/narendra29-05/ml-projects/blob/main/datacleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [56]:
data=pd.read_csv("Bengaluru_House_Data.csv")

data1=data.drop(["area_type","availability","society","balcony"],axis='columns')
data1.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [57]:
data1.isnull().sum()
data2=data1.dropna()
data2.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [58]:
data2["bhk"]=data2["size"].apply(lambda x:int(x.split(" ")[0]))
data2.head()

/tmp/ipython-input-58-566909337.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2["bhk"]=data2["size"].apply(lambda x:int(x.split(" ")[0]))

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [59]:
data2.total_sqft.unique()
data3=data2.copy()

In [60]:
def is_float(x):
  ele=x.split("-")
  if len(ele)==2:
    return (float(ele[0])+float(ele[1]))/2
  try:
    return float(x)
  except:
    return None
data3["total_sqft"]=data3["total_sqft"].apply(is_float)
data3.head()

                   location       size  total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK      1056.0   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom      2600.0   5.0  120.00    4
2               Uttarahalli      3 BHK      1440.0   2.0   62.00    3
3        Lingadheeranahalli      3 BHK      1521.0   3.0   95.00    3
4                  Kothanur      2 BHK      1200.0   2.0   51.00    2

In [61]:
data3.loc[30]

location      Yelahanka
size              4 BHK
total_sqft       2475.0
bath                4.0
price             186.0
bhk                   4
Name: 30, dtype: object

data reductiom

In [66]:
data4=data3.copy()
data4["price_per_unit_sqft"]=data4['price']*100000/data4['total_sqft']
data4.head()

,location,size,total_sqft,bath,price,bhk,price_per_unit_sqft
0,Electronic City Phase II,2 BHK,1056.0,2.0,39.07,2,3699.810606
1,Chikka Tirupathi,4 Bedroom,2600.0,5.0,120.00,4,4615.384615
2,Uttarahalli,3 BHK,1440.0,2.0,62.00,3,4305.555556
3,Lingadheeranahalli,3 BHK,1521.0,3.0,95.00,3,6245.890861
4,Kothanur,2 BHK,1200.0,2.0,51.00,2,4250.000000

In [92]:
data4.location.unique()
data_locations=data4.groupby("location")["location"].agg('count')
data_locations.unique()
len(data_locations[data_locations<=10])
location_less_then_10=data_locations[data_locations<=10]
data5=data4.copy()
data5['location']=data5.location.apply(lambda x : 'other' if x in location_less_then_10 else x )
data5[data5['location']=="other"]

      location       size  total_sqft  bath   price  bhk  price_per_unit_sqft
9        other  6 Bedroom      1020.0   6.0  370.00    6         36274.509804
18       other      3 BHK      2770.0   4.0  290.00    3         10469.314079
19       other      2 BHK      1100.0   2.0   48.00    2          4363.636364
24       other       1 RK       510.0   1.0   25.25    1          4950.980392
25       other      3 BHK      1250.0   3.0   56.00    3          4480.000000
...        ...        ...         ...   ...     ...  ...                  ...
13291    other  1 Bedroom       812.0   1.0   26.00    1          3201.970443
13292    other      3 BHK      1440.0   2.0   63.93    3          4439.583333
13302    other      2 BHK      1075.0   2.0   48.00    2          4465.116279
13306    other  4 Bedroom      1200.0   5.0  325.00    4         27083.333333
13316    other      4 BHK      3600.0   5.0  400.00    4         11111.111111

[2896 rows x 7 columns]